sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t lexarflash8g/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lexarflash8g/react-test npm test

after_success:
  - docker build -t lexarflash8g/multi-client-10-14 ./client
  - docker build -t lexarflash8g/multi-nginx-10-14 ./nginx
  - docker build -t lexarflash8g/multi-server-10-14 ./server
  - docker build -t lexarflash8g/multi-worker-10-14 ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push lexarflash8g/multi-client-10-14
  - docker push lexarflash8g/multi-nginx-10-14
  - docker push lexarflash8g/multi-server-10-14
  - docker push lexarflash8g/multi-worker-10-14

deploy:
  provider: elasticbeanstalk
<<<<<<< HEAD
  region: 'us-east-1'
=======
  region: 'us-east-2'
>>>>>>> f9d9395446baf41988cc15763956ddb20e6b34d5
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-130405883059'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
